openapi: 3.1.0
x-stoplight:
  id: 4hdqb2xlhgr0l
info:
  title: api_for_cms
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  '/cms/node/format/{format_type}':
    get:
      summary: ノードフォーマット取得
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    career:
                      logic_name: キャリアシート
                      biz_type:
                        logic_name: 業種
                        valid:
                          - require
                          - unique
                      overview:
                        logic_name: プロジェクト概要
                        valid:
                          - require
                          - unique
                      detail:
                        logic_name: 担当業務詳細
                        valid:
                          - require
                          - unique
                      term_start:
                        logic_name: 期間開始
                        valid:
                          - require
                          - unique
                          - format_YYYYMMDD
                      term_end:
                        logic_name: 期間終了
                        valid:
                          - unique
                          - format_YYYYMMDD
                      role:
                        logic_name: 役割
                        valid:
                          - require
                          - any
                      phase:
                        logic_name: 工程
                        valid:
                          - require
                          - any
                      scale:
                        logic_name: 規模
                        valid:
                          - unique
                      tech:
                        logic_name: 技術
                        infra:
                          logic_name: インフラ
                          valid:
                            - require
                            - any
                        middle:
                          logic_name: ミドル
                          valid:
                            - require
                            - any
                        strage:
                          logic_name: ストレージ
                          valid:
                            - require
                            - any
                        lang:
                          logic_name: 言語
                          valid:
                            - require
                            - any
                        other:
                          logic_name: その他
                          valid:
                            - any
                properties:
                  career:
                    type: object
                    properties:
                      logic_name:
                        type: string
                      biz_type:
                        type: object
                        properties:
                          logic_name:
                            type: string
                          valid:
                            type: array
                            items:
                              type: string
                      overview:
                        type: object
                        properties:
                          logic_name:
                            type: string
                          valid:
                            type: array
                            items:
                              type: string
                      detail:
                        type: object
                        properties:
                          logic_name:
                            type: string
                          valid:
                            type: array
                            items:
                              type: string
                      term_start:
                        type: object
                        properties:
                          logic_name:
                            type: string
                          valid:
                            type: array
                            items:
                              type: string
                      term_end:
                        type: object
                        properties:
                          logic_name:
                            type: string
                          valid:
                            type: array
                            items:
                              type: string
                      role:
                        type: object
                        properties:
                          logic_name:
                            type: string
                          valid:
                            type: array
                            items:
                              type: string
                      phase:
                        type: object
                        properties:
                          logic_name:
                            type: string
                          valid:
                            type: array
                            items:
                              type: string
                      scale:
                        type: object
                        properties:
                          logic_name:
                            type: string
                          valid:
                            type: array
                            items:
                              type: string
                      tech:
                        type: object
                        properties:
                          logic_name:
                            type: string
                          infra:
                            type: object
                            properties:
                              logic_name:
                                type: string
                              valid:
                                type: array
                                items:
                                  type: string
                          middle:
                            type: object
                            properties:
                              logic_name:
                                type: string
                              valid:
                                type: array
                                items:
                                  type: string
                          strage:
                            type: object
                            properties:
                              logic_name:
                                type: string
                              valid:
                                type: array
                                items:
                                  type: string
                          lang:
                            type: object
                            properties:
                              logic_name:
                                type: string
                              valid:
                                type: array
                                items:
                                  type: string
                          other:
                            type: object
                            properties:
                              logic_name:
                                type: string
                              valid:
                                type: array
                                items:
                                  type: string
                  profile:
                    type: object
                    properties:
                      logic_name:
                        type: string
                      md:
                        type: object
                        properties:
                          logic_name:
                            type: string
                          valid:
                            type:
                              - array
                              - 'null'
                            items:
                              type: string
              examples:
                career:
                  value:
                    career:
                      logic_name: キャリアシート
                      biz_type:
                        logic_name: 業種
                        valid:
                          - require
                          - unique
                      overview:
                        logic_name: プロジェクト概要
                        valid:
                          - require
                          - unique
                      detail:
                        logic_name: 担当業務詳細
                        valid:
                          - require
                          - unique
                      term_start:
                        logic_name: 期間開始
                        valid:
                          - require
                          - unique
                          - format_YYYYMMDD
                      term_end:
                        logic_name: 期間終了
                        valid:
                          - unique
                          - format_YYYYMMDD
                      role:
                        logic_name: 役割
                        valid:
                          - require
                          - any
                      phase:
                        logic_name: 工程
                        valid:
                          - require
                          - any
                      scale:
                        logic_name: 規模
                        valid:
                          - unique
                      tech:
                        logic_name: 技術
                        infra:
                          logic_name: インフラ
                          valid:
                            - require
                            - any
                        middle:
                          logic_name: ミドル
                          valid:
                            - require
                            - any
                        strage:
                          logic_name: ストレージ
                          valid:
                            - require
                            - any
                        lang:
                          logic_name: 言語
                          valid:
                            - require
                            - any
                        other:
                          logic_name: その他
                          valid:
                            - any
                profile:
                  value:
                    profile:
                      logic_name: プロフィール
                      md:
                        logic_name: md
                        valid:
                          - require
                          - unique
                          - blob
        '401':
          description: Unauthorized
        '404':
          description: 指定ノードフォーマットが見つからない
        '500':
          description: Internal Server Error
      operationId: get-cms-node-format
      description: 指定形式タイプに紐づくノードフォーマットを取得する。
    parameters:
      - schema:
          type: string
        name: format_type
        in: path
        description: '形式タイプ（1:キャリアシート、2:プロフィール）'
  /cms/node/list:
    get:
      summary: ノード一覧取得
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  node_list:
                    type: array
                    items:
                      type: object
                      properties:
                        node_id:
                          type: string
                        prent_node_id:
                          type: string
                        key:
                          type: string
                        value:
                          type: string
                        blob_flg:
                          type: string
                        up_dt:
                          type: string
                        rg_dt:
                          type: string
                        version:
                          type: number
                        format_type:
                          type: integer
                        viewable_flg:
                          type: boolean
                        sort_order:
                          type: integer
                      required:
                        - node_id
                        - prent_node_id
                        - key
                        - value
                        - blob_flg
                        - up_dt
                        - rg_dt
                        - version
              examples:
                Example 1:
                  value:
                    node_list:
                      - node_id: string
                        prent_node_id: string
                        key: string
                        value: string
                        blob_flg: string
                        up_dt: string
                        rg_dt: string
                        version: 0
                        format_type: 0
                        viewable_flg: true
                        sort_order: 0
        '401':
          description: Unauthorized
        '500':
          description: Internal Server Error
      operationId: get-cms-node-list
      description: |-
        - ページノードと子ノード、ノードフォーマットをまたいですべてのノードの一覧を取得する。
        - ページノード単位でノード一覧を取得する。
        - 子ノードの表示順序は親-子-孫、親-子-孫の順とする。

        ~~~ ツリー状の見た目
         ROOT 
         　L親１
         　　L子１
         　　　L孫１
         　L親２
         　　L子２
        ~~~

        ~~~ 本APIの取得イメージ
         ROOT 
         親１
         子１
         孫１
         親２
         子２
        ~~~
  '/cms/node/{node_id}':
    get:
      summary: ノード詳細取得
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples:
                  Example 1:
                    node_id: string
                    prent_node_id: string
                    key: string
                    value: string
                    blob_flg: string
                    up_dt: string
                    rg_dt: string
                    version: 0
                    format_type: 0
                    viewable_flg: true
                    sort_order: 0
                properties:
                  node_id:
                    type: string
                  prent_node_id:
                    type: string
                  key:
                    type: string
                  value:
                    type: string
                  blob_flg:
                    type: string
                  up_dt:
                    type: string
                  rg_dt:
                    type: string
                  version:
                    type: integer
                  format_type:
                    type: integer
                  viewable_flg:
                    type: boolean
                  sort_order:
                    type: integer
                required:
                  - node_id
                  - prent_node_id
                  - key
                  - value
                  - blob_flg
                  - up_dt
                  - rg_dt
                  - version
      operationId: get-cms-node
      description: 指定ノードの詳細情報を取得する
    parameters:
      - schema:
          type: string
        name: node_id
        in: path
        required: true
        description: ノードID
    put:
      summary: ノード更新
      operationId: put-cms-node-node_id
      responses:
        '204':
          description: No Content
      description: 指定ノードを更新する。
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
          format: email
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
        createDate:
          type: string
          format: date
          description: The date that the user was created.
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
